//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentClassroom.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebofThingsEntities : DbContext
    {
        public WebofThingsEntities()
            : base("name=WebofThingsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actuator> Actuator { get; set; }
        public virtual DbSet<Command> Command { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<Sensor> Sensor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
