//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentClassroom.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> Device_Ref { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
